public_services: # acteurs
  siao:
    title: SIAO (Services Intégrés de l’Accueil et de l’Orientation)  # titre, nom de l'acteur
    description: "Le Service intégré de l’accueil et de l’orientation (SIAO) centralise sur chaque territoire la demande et l’offre d’hébergement  pour apporter à chaque demande (urgente ou moins urgente) la réponse la plus adaptée d’hébergement, de logement accompagné ou de logement ordinaire. En cas d’urgence (pour une nuit), un seul numéro à composer : le 115"
    postal_address:  47 rue Docteur Schweitzer, 51100 Reims # adresse postale
    email: siao51@orange.fr
    phone: 03 26 02 30 97 # téléphone
    url:
    offer: # offre de service, ajouter « - » pour énumerer
      - Trouver un logement pour une nuit
      - Etre accompagné.e pour trouver une solution d'hébergement plus stable

  crous:
    title: CROUS (Centre régional des œuvres universitaires et scolaires) de la Marne (51) # titre, nom de l'acteur
    description: Le Crous, opérateur du service public de la vie étudiante, a pour missions principales, le logement étudiant, la restauration universitaire des étudiants et l’action sociale à travers les bourses et le Fond d’Aide d’Urgence (FNAU). # description général de l'acteur
    postal_address: 31 rue du général Sarrail, 51100 Reims
    email: reims-campus@crous-reims.fr
    phone:  03 26 50 04 59 # téléphone
    url: http://www.crous-reims.fr/
    offer: # offre de service, ajouter « - » pour énumerer
      # - ouvert du lundi au vendredi (8h30 – 12h et 13h – 17h)
      # - http://www.crous-reims.fr/contact/
      - T'informer sur le logement en résidence universitaire
      - Faire le suivi de ton Dossier Social Étudiant
      # - "Propose des rendez-vous à l’Espace Reims Campus : http://www.crous-reims.fr/service/reims-campus ."

  paindavoine:
    title: FJT (Foyer de Jeunes Travailleurs) Léon Paindavoine  # titre, nom de l'acteur
    description: Les foyers de jeunes travailleurs (FJT) ont pour mission d'accueillir des jeunes en formation ou exerçant une activité professionnelle. Ils proposent un hébergement temporaire comportant à la fois des locaux privatifs (meublés ou non) et des locaux communs affectés à la vie collective. Ils  s'adressent essentiellement aux jeunes travailleurs vivant seuls, âgés de 16 à 25 ans et exerçant une activité professionnelle ou suivant une formation professionnelle (par ex. stage ou apprentissage). Certains établissements accueillent également des étudiants ou des demandeurs d'emploiLa durée de l'hébergement est généralement de 2 ans maximum. # description général de l'acteur
    postal_address: 1 rue du Lieut Herduin, 51100 Reims # adresse postale
    email: residence.paindavoine@noelpaindavoine.fr
    phone:  03 26 61 48 00 # téléphone
    url:
    offer: # offre de service, ajouter « - » pour énumerer
      - Trouver différents types de logements en foyer
      - T'aider à trouver une solution logement sur ton territoire


  action_logement:
    title: Action Logement # titre, nom de l'acteur
    description: Action Logement (ex 1% Logement) gère la Participation des Employeurs à l’Effort de Construction (PEEC). # description général de l'acteur
    postal_address: Agence Aliance Territoires 38 rue Cérès, 51100 Reims # adresse postale
    email: agence.reims@alianceterritoires.fR
    phone: 03 26 04 29 38  # téléphone
    url: http://www.alianceterritoires.fr/
    offer: # offre de service, ajouter « - » pour énumerer
      - Te proposer une offre de logements à louer
      - Te proposer une offre de logement pour tous les budgets


  caf:
    title: CAF (Caisse d'Allocations Familiales)
    description: La CAF les aides au logement (APL)   . # description général de l'acteur
    postal_address: 202 Rue des Capucins, 51087 Reims
    email:
    phone: 0 810 25 51 10
    url: https://www.caf.fr/ma-caf/caf-de-la-marne/points-d-accueil/reims
    offer: # offre de service, ajouter « - » pour énumerer
      - Simuler le montant de son APL
      - T'aider à remplir la demande d'APL


  crij:
    title: CRIJ (Centre Régional d'Information Jeunesse)
    description: Le CRIJ de Reims accueille, informe et conseille les jeunes et tous les publics dans tous les domaines qui les intéressent. # description général de l'acteur
    postal_address: 41 rue de Talleyrand 51100 Reims 
    email: ijca@crij-ca.fr
    phone: 03 26 79 84 79 
    url: jeunes-ca.fr
    offer: # offre de service, ajouter « - » pour énumerer
      - Découvrir les solutions logement sur mon 
  
measures: # dispositifs, aides
  cent_quinze:
    title: 115
    description: Le 115 est un numéro d'urgence à n'utiliser que si vous êtes sans possibilité d'hébergement au moment de l'appel. N'appelez pas le 115 tant que vous disposez encore d'un logement ou êtes logé chez un tiers. Le 115 octroie des places au jour le jour.
    phone: 115
    url: http://www.gouvernement.fr/sites/default/files/contenu/piece-jointe/2014/10/dihal_-_annuaire_siao_ecran.pdf
    public_service: siao # facultatif, acteur du dispositif / de l'aide

  apl:
    title: L’APL (Aide personnalisée au logement)
    description: L’APL est une aide au paiement des loyers qui est délivrée par la CAF (peut être remplacée par l'Allocation logement à caractère social (ALS) si le logement n'est pas conventionné par l'Etat.
    url: http://www.caf.fr/aides-et-services/les-services-en-ligne/estimer-vos-droits
    public_service: caf # facultatif, acteur du dispositif / de l'aide

  cle:
    title: La CLÉ (caution locative étudiante)
    description: La Clé est une garantie de l'Etat qui permet aux étudiants dépourvus de garants personnels de faciliter leur accès à un logement. La Clé est gérée par les Crous.
    url: http://www.lokaviz.fr/n/a-qui-s-adresse-la-cle/n:473
    public_service: crous # facultatif, acteur du dispositif / de l'aide

  locapass:
    title: Garantie Loca-Pass
    description: Caution accordée au locataire pour prendre en charge le paiement du loyer et des charges de sa résidence principale en cas de défaillance pour les jeunes de moins de 30 ans.
    url: http://www.actionlogement.fr/media/upload/Fiches_Produits_2015/PP/20150409GarantieLOCA-PASS.pdf
    public_service: action_logement # facultatif, acteur du dispositif / de l'aide
    ext:
      - Facilite l’entrée du locataire dans son logement.
      - Couvre, pendant 3 ans, le locataire en cas de difficultés de paiement de son loyer
      - Rassure le bailleur
      - Engagement gratuit

  visale:
    title: Garantie VISALE locataire et bailleur
    description: La garantie Visale est un engagement gratuit pour le locataire et le bailleur. Le dispositif vise à couvrir les impayés de loyers (charges comprises) du locataire, quelle qu'en soit la cause au cours des trois premières années du bail et dans la limite du départ du locataire
    url: https://www.visale.fr/#/
    public_service: action_logement # facultatif, acteur du dispositif / de l'aide
    ext:
      - Propose une garantie fiable pour le propriétaire, ce qui me dispense de toute autre caution physique ou morale
      - Propose unsuivi personnalisé et réactif via un espace personnel en ligne sur https://www.visale.fr/#/

